### ISSUE TITLE
Running graphical applications?

### ISSUE THREAD

**Issue by q2dg** [nmilosev/anyfed#1]
Hello.
I'd like to run firefox into anyfed system. If I install it and I run it, I get a "Error: GDK_BACKEND does not match available displays" . So I do export DISPLAY=:0.0 and then I get this error:

Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
process 2886: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
  D-Bus not built with -rdynamic so unable to print a backtrace
Redirecting call to abort() to mozalloc_abort
Segmentation fault (core dumped)

So it seems it's not so easy

So I've though an alternative: I've thought installing a ssh server in anyfed system woud do the trick if I connect to it with "ssh -X " command, but I see host system and anyfed system share the same IP, so, how could I connect to anyfed system from host system?

Thanks!

**Comment by nmilosev** [comment]
Hello, thanks for reporting this. 

For running gui applications, you need to set `export DISPLAY=:0` and to do (only once) `dbus-uuidgen > /etc/machine-id`

I'm guessing you are running the non-root option? You could set up ssh, but you would need to configure it to use another (higher) port (ex. 5000) then `ssh localhost:5000 -l root` should  work.

Please report back. 

Thanks!

**Comment by q2dg** [comment]
Ooooh, yes!!! It works! It's amazing!!
Thanks a lot!!! What a wonderful piece of software!!
Thanks!

**Comment by nmilosev** [comment]
Glad it is working for you!

Cheers!
