### ISSUE TITLE
Minimal kernel requirement for android phone side

### ISSUE THREAD

**Issue by onuralpszr** [nmilosev/anyfed#2]
Hello; 

Android 6.0 non-root phone is not enough requirement for that readme. We also need at least kernel 3.10 or above version of it. Please fix it.

Source : https://docs.docker.com/engine/installation/binaries/

""""
A 3.10 Linux kernel is the minimum requirement for Docker. Kernels older than 3.10 lack some of the features required to run Docker containers. These older versions are known to have bugs which cause data loss and frequently panic under certain conditions.
""""

**Comment by nmilosev** [comment]
Dear Onur, 

it is not using docker on the phone. We are using a rootfs for Docker with a simple chroot or proot (depends on the root availability). It should work with almost all kernels. :)
