### ISSUE TITLE
Unable to download `proot`

### ISSUE THREAD

**Issue by gbraad** [nmilosev/anyfed#3]
The address `static.proot.me` can not be resolved. All links on https://proot-me.github.io/ are not working.

**Comment by gbraad** [comment]
https://github.com/proot-me/PRoot/issues/118

**Comment by gbraad** [comment]
https://github.com/proot-me/proot-static-build/releases

**Comment by nmilosev** [comment]
Thanks for reporting!

Pushed a fix, please test.

**Comment by gbraad** [comment]
Hadn't noticed the reply... sorry. Works fine
